//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calendar()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public Nullable<long> IdWorkingCalendar { get; set; }
        public Nullable<int> IdLearningCalendar { get; set; }
        public Nullable<int> IdVacationCalendar { get; set; }
    
        public virtual LearningCalendar LearningCalendar { get; set; }
        public virtual VacationCalendar VacationCalendar { get; set; }
        public virtual WorkingCalendar WorkingCalendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
