//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee1 = new HashSet<Employee>();
            this.Employee11 = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string PersonalPhone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int IdEmployeeDepartment { get; set; }
        public int IdPosition { get; set; }
        public Nullable<int> DirectSupervisor { get; set; }
        public Nullable<int> AssistantEmployee { get; set; }
        public string WorkPhone { get; set; }
        public string Email { get; set; }
        public string EmployeeOffice { get; set; }
        public string Other { get; set; }
        public Nullable<int> CalendarEmployee { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee11 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual Position Position { get; set; }
    }
}
