//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HrEvent()
        {
            this.LearningCalendar = new HashSet<LearningCalendar>();
        }
    
        public int Id { get; set; }
        public int typeEventId { get; set; }
        public string EventStatus { get; set; }
        public System.DateTime DateEvent { get; set; }
        public string ResponsiblePerson { get; set; }
        public string DescriptionEvent { get; set; }
    
        public virtual typeEvent typeEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LearningCalendar> LearningCalendar { get; set; }
    }
}
