//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HrManagementEntities : DbContext
    {
        public HrManagementEntities()
            : base("name=HrManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<HrEvent> HrEvent { get; set; }
        public virtual DbSet<LearningCalendar> LearningCalendar { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<typeEvent> typeEvent { get; set; }
        public virtual DbSet<VacationCalendar> VacationCalendar { get; set; }
        public virtual DbSet<WorkingCalendar> WorkingCalendar { get; set; }
    }
}
