//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.LearningCalendar = new HashSet<LearningCalendar>();
        }
    
        public int Id { get; set; }
        public string NameMaterial { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string StatusMaterial { get; set; }
        public string TypeMaterial { get; set; }
        public string AreaMaterial { get; set; }
        public string AuthorMaterial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LearningCalendar> LearningCalendar { get; set; }
    }
}
